-- Pizza Passport — Pizzerias & Moments schema (additive migration)
-- Run this in the Supabase Dashboard AFTER schema.sql and schema_social.sql.
-- Safe to re-run (every statement is idempotent).
--
-- Adds:
--   * public.pizzerias — normalizes "which venue" out of free-text
--     restaurant_name into a real, shareable entity keyed by place_id, so
--     Moments (and future drops/collections) can group by place.
--   * entries.place_id gets backfilled + a real foreign key to pizzerias.
--   * entries.serial_number — an auto-incrementing display serial
--     ("Stamp No. 4821"), and entries.claim_method, recording how each
--     stamp was earned (geo today; qr/link/secret_word reserved for the
--     claim-methods phase in schema_drops.sql).
--   * public.moments — the optional photo+note a user attaches to a
--     check-in after the fact, grouped under its pizzeria.
--
-- ============================================================
-- pizzerias
-- ============================================================
create table if not exists public.pizzerias (
  place_id    text primary key,
  name        text not null,
  latitude    double precision,
  longitude   double precision,
  created_at  timestamptz not null default now()
);

alter table public.pizzerias enable row level security;

create policy "Pizzerias are publicly readable"
  on public.pizzerias for select
  using (true);

-- No direct insert/update policy: rows are only ever created by the
-- security-definer trigger below, keyed off a real check-in.

-- Backfill from whatever entries already exist (no-op on a fresh install),
-- then attach the foreign key. A plain INSERT (not a trigger) is enough
-- here since this only needs to run once, at migration time.
insert into public.pizzerias (place_id, name, latitude, longitude)
select distinct on (place_id) place_id, restaurant_name, latitude, longitude
from public.entries
where place_id is not null
order by place_id, created_at asc
on conflict (place_id) do nothing;

alter table public.entries drop constraint if exists entries_place_id_fkey;
alter table public.entries
  add constraint entries_place_id_fkey foreign key (place_id) references public.pizzerias (place_id);

-- Keeps `pizzerias` in sync going forward: the first check-in at a given
-- place_id defines its canonical name/coordinates; later check-ins there
-- just reference the existing row.
create or replace function public.sync_pizzeria_from_entry()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.place_id is not null then
    insert into public.pizzerias (place_id, name, latitude, longitude)
    values (new.place_id, new.restaurant_name, new.latitude, new.longitude)
    on conflict (place_id) do nothing;
  end if;
  return new;
end;
$$;

-- Must run before trg_enforce_checkin_rate_limit / trg_log_checkin_activity
-- from schema_social.sql conceptually, but trigger execution order for
-- multiple BEFORE INSERT triggers on the same table is alphabetical by
-- trigger name in Postgres — "sync_pizzeria" sorts before neither of those
-- (they're a BEFORE and an AFTER trigger respectively, so no conflict) and
-- entries.place_id is only *read* by this trigger, not written, so
-- ordering relative to the rate-limit trigger doesn't matter either way.
drop trigger if exists trg_sync_pizzeria_from_entry on public.entries;
create trigger trg_sync_pizzeria_from_entry
  before insert on public.entries
  for each row execute function public.sync_pizzeria_from_entry();

-- ============================================================
-- entries: stamp identity metadata
-- ============================================================
alter table public.entries add column if not exists serial_number bigint generated by default as identity;
alter table public.entries add column if not exists claim_method text not null default 'geo'
  check (claim_method in ('geo', 'manual', 'qr', 'link', 'secret_word'));

comment on column public.entries.serial_number is
  'Human-readable display serial ("Stamp No. 4821") — auto-assigned, sequential across all users.';
comment on column public.entries.claim_method is
  'How this stamp was earned. Only geo/manual are reachable from the UI today; qr/link/secret_word are reserved for the official-drops claim-methods phase (see schema_drops.sql).';

-- ============================================================
-- moments
-- A moment always belongs to exactly one check-in (entry) and therefore
-- one user; place_id is denormalized from the entry for fast "moments at
-- this pizzeria" queries without joining through entries every time.
-- ============================================================
create table if not exists public.moments (
  id         uuid primary key default gen_random_uuid(),
  entry_id   uuid not null references public.entries (id) on delete cascade,
  user_id    uuid not null references public.profiles (id) on delete cascade,
  place_id   text references public.pizzerias (place_id),
  photo_url  text,
  note       text,
  created_at timestamptz not null default now(),
  constraint moments_has_content check (photo_url is not null or note is not null)
);

create index if not exists moments_entry_idx on public.moments (entry_id);
create index if not exists moments_place_idx on public.moments (place_id, created_at desc);
create index if not exists moments_user_idx on public.moments (user_id, created_at desc);

alter table public.moments enable row level security;

-- Same visibility rule as entries: public passports show their moments to
-- everyone, private ones only to the owner and accepted friends. This is
-- what makes a pizzeria's aggregated Moments view "public-only" in
-- practice — the page itself has no separate privacy flag, it just shows
-- whatever moments RLS lets the viewer see.
create policy "Moments are readable if the author is public, self, or friend"
  on public.moments for select
  using (
    user_id = auth.uid()
    or public.are_friends(auth.uid(), user_id)
    or exists (select 1 from public.profiles p where p.id = moments.user_id and p.is_public)
  );

create policy "Users can add moments to their own entries"
  on public.moments for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and exists (select 1 from public.entries e where e.id = entry_id and e.user_id = auth.uid())
  );

create policy "Users can update their own moments"
  on public.moments for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own moments"
  on public.moments for delete
  to authenticated
  using (auth.uid() = user_id);
